name: lcs
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  - ipympl  # interactive matplotlib plots
  - seaborn
  - pip:
     - -e .  # install git checkout of lcs in editable mode

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - jupytext
